export const CONSUMER_KEY = process.env.REACT_APP_CONSUMER_KEY;
export const OAUTH_VERSION = "1.0";
export const SIGNATURE_METHOD = "HMAC-SHA1";
export const CONSUMER_SECRET = process.env.REACT_APP_CONSUMER_SECRET;
export const REQUEST_TOKEN_URL = "https://api.twitter.com/oauth/request_token";
export const ACCESS_TOKEN_URL = "https://api.twitter.com/oauth/access_token";
export const CORS_BYPASS_URL = "https://cors-anywhere.herokuapp.com";
export const AUTHENTICATE_URL = "https://api.twitter.com/oauth/authenticate";

export const mockTweets = [
  {
    created_at: "Sat Jun 13 06:21:43 +0000 2020",
    id: 1271689185800401000,
    id_str: "1271689185800400896",
    full_text:
      "Juventus reach Coppa Italia final after stalemate with 10-man Milan despite Ronaldo penalty miss https://t.co/K3C7wl53Y9",
    truncated: false,
    display_text_range: [0, 120],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/K3C7wl53Y9",
          expanded_url:
            "https://www.theguardian.com/football/2020/jun/12/juventus-reach-coppa-italia-final-after-stalemate-despite-ronaldo-penalty-miss?CMP=share_btn_tw",
          display_url: "theguardian.com/football/2020/…",
          indices: [97, 120],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 46403451,
      id_str: "46403451",
      name: "Guardian sport",
      screen_name: "guardian_sport",
      location: "London",
      description:
        "Sport news, comment, video and more from the @Guardian. For all your US sports needs, follow @GdnUSsports, and Australian sport @GdnAusSport. IG: guardian_sport",
      url: "https://t.co/YJoNLFSjE2",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YJoNLFSjE2",
              expanded_url: "http://www.theguardian.com/sport",
              display_url: "theguardian.com/sport",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 814882,
      friends_count: 1759,
      listed_count: 8745,
      created_at: "Thu Jun 11 14:55:04 +0000 2009",
      favourites_count: 296,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 209742,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/46403451/1542987487",
      profile_link_color: "005689",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:20:25 +0000 2020",
    id: 1271688859441643500,
    id_str: "1271688859441643520",
    full_text:
      "Premier League restart preview No 10: Liverpool. By @AHunterGuardian https://t.co/soG4SsZNGs",
    truncated: false,
    display_text_range: [0, 92],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "AHunterGuardian",
          name: "Andy Hunter",
          id: 718463598,
          id_str: "718463598",
          indices: [52, 68],
        },
      ],
      urls: [
        {
          url: "https://t.co/soG4SsZNGs",
          expanded_url:
            "https://www.theguardian.com/football/2020/jun/12/premier-league-restart-preview-no-liverpool?CMP=share_btn_tw",
          display_url: "theguardian.com/football/2020/…",
          indices: [69, 92],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 46403451,
      id_str: "46403451",
      name: "Guardian sport",
      screen_name: "guardian_sport",
      location: "London",
      description:
        "Sport news, comment, video and more from the @Guardian. For all your US sports needs, follow @GdnUSsports, and Australian sport @GdnAusSport. IG: guardian_sport",
      url: "https://t.co/YJoNLFSjE2",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YJoNLFSjE2",
              expanded_url: "http://www.theguardian.com/sport",
              display_url: "theguardian.com/sport",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 814882,
      friends_count: 1759,
      listed_count: 8745,
      created_at: "Thu Jun 11 14:55:04 +0000 2009",
      favourites_count: 296,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 209742,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/46403451/1542987487",
      profile_link_color: "005689",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:20:02 +0000 2020",
    id: 1271688763932999700,
    id_str: "1271688763932999681",
    full_text:
      "RT @jnajefferson: T- Thank\nG- God\nI- It’s\nF- Find The Cops That Killed Breonna Taylor and Arrest Them Immediately",
    truncated: false,
    display_text_range: [0, 113],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "jnajefferson",
          name: "J'na Jefferson",
          id: 542153805,
          id_str: "542153805",
          indices: [3, 16],
        },
      ],
      urls: [],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 346524052,
      id_str: "346524052",
      name: "Haley O'Shaughnessy",
      screen_name: "HaleyOSomething",
      location: "Louisville, KY",
      description: "writer @ringer. can you pass the hot sauce?",
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 66226,
      friends_count: 1140,
      listed_count: 898,
      created_at: "Mon Aug 01 12:06:16 +0000 2011",
      favourites_count: 15626,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 17790,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1211390516597796869/VGzDhV6k_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1211390516597796869/VGzDhV6k_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/346524052/1470623963",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Fri Jun 12 23:02:06 +0000 2020",
      id: 1271578553281372200,
      id_str: "1271578553281372160",
      full_text:
        "T- Thank\nG- God\nI- It’s\nF- Find The Cops That Killed Breonna Taylor and Arrest Them Immediately",
      truncated: false,
      display_text_range: [0, 95],
      entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 542153805,
        id_str: "542153805",
        name: "J'na Jefferson",
        screen_name: "jnajefferson",
        location: "“Jay-nuh” ",
        description:
          "Waiting on my Beyoncé retweet • ✍🏾/🎥/🎙: @theroot @billboard @bbc_culture @MTVNEWS @AccessOnline @BUILDSeriesNYC @bbcfrontrow+ 💌: jna.m.jefferson@gmail.com",
        url: "https://t.co/pid1iWqkF2",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/pid1iWqkF2",
                expanded_url: "https://www.jnajefferson.com",
                display_url: "jnajefferson.com",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 2664,
        friends_count: 996,
        listed_count: 21,
        created_at: "Sat Mar 31 23:32:34 +0000 2012",
        favourites_count: 1849,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 11667,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "642D8B",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1267811250265886722/gl-Igiy1_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1267811250265886722/gl-Igiy1_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/542153805/1588286352",
        profile_link_color: "8B1BDB",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 662,
      favorite_count: 845,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    is_quote_status: false,
    retweet_count: 662,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:19:45 +0000 2020",
    id: 1271688689941229600,
    id_str: "1271688689941229569",
    full_text:
      "I swear needing to have a take on everything makes these people's brains melt into paste https://t.co/EQ3uCSjlhh",
    truncated: false,
    display_text_range: [0, 88],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/EQ3uCSjlhh",
          expanded_url:
            "https://twitter.com/LucasJHann/status/1271684883946049536",
          display_url: "twitter.com/LucasJHann/sta…",
          indices: [89, 112],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 345762803,
      id_str: "345762803",
      name: "Harrison Faigen",
      screen_name: "hmfaigen",
      location: "A roaming tower of giraffes",
      description:
        "Lakers Beat Writer/Editor-in-Chief @LakersSBN. @RewindReconsidr co-host (link in bio). Proud @csuf alum. Requests/tips harrison.faigen@sbnation.com",
      url: "https://t.co/1KwqxoQL7s",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/1KwqxoQL7s",
              expanded_url:
                "https://open.spotify.com/show/0GwblTxJG4Nwk4ljzTvSUd?si=LoFSY-oESGu7mKhwz5duMQ",
              display_url: "open.spotify.com/show/0GwblTxJG…",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 29991,
      friends_count: 913,
      listed_count: 842,
      created_at: "Sun Jul 31 03:59:03 +0000 2011",
      favourites_count: 48262,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 23999,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: true,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/926151905012695040/g0DCP7yQ_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/926151905012695040/g0DCP7yQ_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/345762803/1562518866",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1271684883946049500,
    quoted_status_id_str: "1271684883946049536",
    quoted_status_permalink: {
      url: "https://t.co/EQ3uCSjlhh",
      expanded: "https://twitter.com/LucasJHann/status/1271684883946049536",
      display: "twitter.com/LucasJHann/sta…",
    },
    quoted_status: {
      created_at: "Sat Jun 13 06:04:37 +0000 2020",
      id: 1271684883946049500,
      id_str: "1271684883946049536",
      full_text: "L @GottliebShow https://t.co/xHNs8rCl3T",
      truncated: false,
      display_text_range: [0, 15],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "GottliebShow",
            name: "Doug Gottlieb",
            id: 34930912,
            id_str: "34930912",
            indices: [2, 15],
          },
        ],
        urls: [
          {
            url: "https://t.co/xHNs8rCl3T",
            expanded_url:
              "https://twitter.com/BigBlueTheory/status/1271681072292454401",
            display_url: "twitter.com/BigBlueTheory/…",
            indices: [16, 39],
          },
        ],
      },
      source:
        '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 144550106,
        id_str: "144550106",
        name: "Lucas",
        screen_name: "LucasJHann",
        location: "Rent free in your head ",
        description:
          "agitator.educator.advocate. I ran the biggest Clippers blog on the web for 5 years. then I started an independent sports site @213Hoops. lucashann@213Hoops.com",
        url: "https://t.co/w0Ge9UBJBI",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/w0Ge9UBJBI",
                expanded_url: "https://www.patreon.com/213hoops",
                display_url: "patreon.com/213hoops",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 3530,
        friends_count: 417,
        listed_count: 145,
        created_at: "Sun May 16 16:35:36 +0000 2010",
        favourites_count: 21739,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 28260,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1166136732926009345/yV7tfg7g_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1166136732926009345/yV7tfg7g_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/144550106/1590404374",
        profile_link_color: "007AB3",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: true,
      quoted_status_id: 1271681072292454400,
      quoted_status_id_str: "1271681072292454401",
      quoted_status_permalink: {
        url: "https://t.co/xHNs8rCl3T",
        expanded:
          "https://twitter.com/BigBlueTheory/status/1271681072292454401",
        display: "twitter.com/BigBlueTheory/…",
      },
      retweet_count: 0,
      favorite_count: 3,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: "und",
    },
    retweet_count: 0,
    favorite_count: 4,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:19:27 +0000 2020",
    id: 1271688616478036000,
    id_str: "1271688616478035969",
    full_text: "i can’t stop laughing at this https://t.co/CxsOmaJgh2",
    truncated: false,
    display_text_range: [0, 29],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/CxsOmaJgh2",
          expanded_url:
            "https://twitter.com/camundell1/status/1271687116603285504",
          display_url: "twitter.com/camundell1/sta…",
          indices: [30, 53],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 346524052,
      id_str: "346524052",
      name: "Haley O'Shaughnessy",
      screen_name: "HaleyOSomething",
      location: "Louisville, KY",
      description: "writer @ringer. can you pass the hot sauce?",
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 66226,
      friends_count: 1140,
      listed_count: 898,
      created_at: "Mon Aug 01 12:06:16 +0000 2011",
      favourites_count: 15626,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 17790,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1211390516597796869/VGzDhV6k_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1211390516597796869/VGzDhV6k_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/346524052/1470623963",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1271687116603285500,
    quoted_status_id_str: "1271687116603285504",
    quoted_status_permalink: {
      url: "https://t.co/CxsOmaJgh2",
      expanded: "https://twitter.com/camundell1/status/1271687116603285504",
      display: "twitter.com/camundell1/sta…",
    },
    quoted_status: {
      created_at: "Sat Jun 13 06:13:30 +0000 2020",
      id: 1271687116603285500,
      id_str: "1271687116603285504",
      full_text:
        "@GottliebShow @HaleyOSomething I think Kyrie has realized he is at best a second option and scared of the big stage.  And he’s weird.  So this is a way out.",
      truncated: false,
      display_text_range: [31, 156],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "GottliebShow",
            name: "Doug Gottlieb",
            id: 34930912,
            id_str: "34930912",
            indices: [0, 13],
          },
          {
            screen_name: "HaleyOSomething",
            name: "Haley O'Shaughnessy",
            id: 346524052,
            id_str: "346524052",
            indices: [14, 30],
          },
        ],
        urls: [],
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: 1271686689048588300,
      in_reply_to_status_id_str: "1271686689048588288",
      in_reply_to_user_id: 34930912,
      in_reply_to_user_id_str: "34930912",
      in_reply_to_screen_name: "GottliebShow",
      user: {
        id: 1936118412,
        id_str: "1936118412",
        name: "Casey Allen",
        screen_name: "camundell1",
        location: "",
        description: "",
        url: null,
        entities: { description: { urls: [] } },
        protected: false,
        followers_count: 51,
        friends_count: 540,
        listed_count: 0,
        created_at: "Sat Oct 05 02:28:50 +0000 2013",
        favourites_count: 2502,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 227,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1098822561679331328/X0lVoKul_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1098822561679331328/X0lVoKul_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/1936118412/1511236562",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    retweet_count: 0,
    favorite_count: 6,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:19:23 +0000 2020",
    id: 1271688599562588200,
    id_str: "1271688599562588160",
    full_text:
      "RT @07reddevilz: Except for 2 people in this photo. The rest of them are all friends I met on Twitter. Not able to tag you @aakashbhatt97 h…",
    truncated: false,
    display_text_range: [0, 140],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "07reddevilz",
          name: "Raj",
          id: 36418033,
          id_str: "36418033",
          indices: [3, 15],
        },
        {
          screen_name: "aakashbhatt97",
          name: "Aakash Bhatt",
          id: 1389657205,
          id_str: "1389657205",
          indices: [123, 137],
        },
      ],
      urls: [],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 805292401,
      id_str: "805292401",
      name: "A Girl In Red",
      screen_name: "maria_mufc",
      location: "India,Mumbai",
      description:
        "@manutd is LOVE #GGMU |\n❤ Makaveli | Giggssyy |\n|Dimitar Berbatov | Insta:mariamufc | Proud Muslim | snapchat: maria_mufc",
      url: "https://t.co/sSyX5g9KzK",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/sSyX5g9KzK",
              expanded_url: "http://agirlinred.com",
              display_url: "agirlinred.com",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 1638,
      friends_count: 1547,
      listed_count: 8,
      created_at: "Wed Sep 05 20:07:42 +0000 2012",
      favourites_count: 1464,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 12113,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: true,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/955072253435129857/9wXiZJav_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/955072253435129857/9wXiZJav_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/805292401/1551777707",
      profile_link_color: "B30000",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "regular",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Sun May 17 04:24:22 +0000 2020",
      id: 1261875183498850300,
      id_str: "1261875183498850304",
      full_text:
        "Except for 2 people in this photo. The rest of them are all friends I met on Twitter. Not able to tag you @aakashbhatt97 https://t.co/xy2I1pRQzu https://t.co/AUf8P5NGEU",
      truncated: false,
      display_text_range: [0, 144],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "aakashbhatt97",
            name: "Aakash Bhatt",
            id: 1389657205,
            id_str: "1389657205",
            indices: [106, 120],
          },
        ],
        urls: [
          {
            url: "https://t.co/xy2I1pRQzu",
            expanded_url:
              "https://twitter.com/hashplanted/status/1260988566676668422",
            display_url: "twitter.com/hashplanted/st…",
            indices: [121, 144],
          },
        ],
        media: [
          {
            id: 1261875167053009000,
            id_str: "1261875167053008897",
            indices: [145, 168],
            media_url: "http://pbs.twimg.com/media/EYMUx1sU0AEtENN.jpg",
            media_url_https: "https://pbs.twimg.com/media/EYMUx1sU0AEtENN.jpg",
            url: "https://t.co/AUf8P5NGEU",
            display_url: "pic.twitter.com/AUf8P5NGEU",
            expanded_url:
              "https://twitter.com/07reddevilz/status/1261875183498850304/photo/1",
            type: "photo",
            sizes: {
              thumb: { w: 150, h: 150, resize: "crop" },
              small: { w: 680, h: 510, resize: "fit" },
              large: { w: 1024, h: 768, resize: "fit" },
              medium: { w: 1024, h: 768, resize: "fit" },
            },
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1261875167053009000,
            id_str: "1261875167053008897",
            indices: [145, 168],
            media_url: "http://pbs.twimg.com/media/EYMUx1sU0AEtENN.jpg",
            media_url_https: "https://pbs.twimg.com/media/EYMUx1sU0AEtENN.jpg",
            url: "https://t.co/AUf8P5NGEU",
            display_url: "pic.twitter.com/AUf8P5NGEU",
            expanded_url:
              "https://twitter.com/07reddevilz/status/1261875183498850304/photo/1",
            type: "photo",
            sizes: {
              thumb: { w: 150, h: 150, resize: "crop" },
              small: { w: 680, h: 510, resize: "fit" },
              large: { w: 1024, h: 768, resize: "fit" },
              medium: { w: 1024, h: 768, resize: "fit" },
            },
          },
        ],
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 36418033,
        id_str: "36418033",
        name: "Raj",
        screen_name: "07reddevilz",
        location: "India",
        description:
          "MUFC is my Home. Totally adore @RafaelNadal #Vettel. Love Nolan Movies #VamosRafa #GGMU #Lebron #WayneRooney #Ferrari #CSK #MSD",
        url: null,
        entities: { description: { urls: [] } },
        protected: false,
        followers_count: 2135,
        friends_count: 1882,
        listed_count: 26,
        created_at: "Wed Apr 29 17:35:18 +0000 2009",
        favourites_count: 14764,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 106120,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1271097292989349888/ATilpL_Q_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1271097292989349888/ATilpL_Q_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/36418033/1437540283",
        profile_link_color: "0084B4",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: true,
      quoted_status_id: 1260988566676668400,
      quoted_status_id_str: "1260988566676668422",
      quoted_status_permalink: {
        url: "https://t.co/xy2I1pRQzu",
        expanded: "https://twitter.com/hashplanted/status/1260988566676668422",
        display: "twitter.com/hashplanted/st…",
      },
      quoted_status: {
        created_at: "Thu May 14 17:41:16 +0000 2020",
        id: 1260988566676668400,
        id_str: "1260988566676668422",
        full_text:
          "serious question here; has anyone ever found a friend through twitter and actually met up with them?",
        truncated: false,
        display_text_range: [0, 100],
        entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
        source:
          '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
          id: 1891281302,
          id_str: "1891281302",
          name: "luca",
          screen_name: "hashplanted",
          location: "",
          description: "knows how to read and is learning how to science",
          url: null,
          entities: { description: { urls: [] } },
          protected: false,
          followers_count: 5236,
          friends_count: 1097,
          listed_count: 0,
          created_at: "Sat Sep 21 19:55:31 +0000 2013",
          favourites_count: 35065,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: false,
          statuses_count: 8151,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "C0DEED",
          profile_background_image_url:
            "http://abs.twimg.com/images/themes/theme1/bg.png",
          profile_background_image_url_https:
            "https://abs.twimg.com/images/themes/theme1/bg.png",
          profile_background_tile: false,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1176220893405732864/p-weogHN_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1176220893405732864/p-weogHN_normal.jpg",
          profile_link_color: "1DA1F2",
          profile_sidebar_border_color: "C0DEED",
          profile_sidebar_fill_color: "DDEEF6",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: false,
          default_profile: true,
          default_profile_image: false,
          following: false,
          follow_request_sent: false,
          notifications: false,
          translator_type: "none",
        },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 9560,
        favorite_count: 137182,
        favorited: false,
        retweeted: false,
        lang: "en",
      },
      retweet_count: 1,
      favorite_count: 14,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: "en",
    },
    is_quote_status: true,
    quoted_status_id: 1260988566676668400,
    quoted_status_id_str: "1260988566676668422",
    quoted_status_permalink: {
      url: "https://t.co/xy2I1pRQzu",
      expanded: "https://twitter.com/hashplanted/status/1260988566676668422",
      display: "twitter.com/hashplanted/st…",
    },
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:19:02 +0000 2020",
    id: 1271688510001553400,
    id_str: "1271688510001553410",
    full_text:
      "Premier League restart preview No 11: Manchester City. By @paulwilsongnm https://t.co/pmnQwhydj0",
    truncated: false,
    display_text_range: [0, 96],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "paulwilsongnm",
          name: "Paul Wilson",
          id: 599350038,
          id_str: "599350038",
          indices: [58, 72],
        },
      ],
      urls: [
        {
          url: "https://t.co/pmnQwhydj0",
          expanded_url:
            "https://www.theguardian.com/football/2020/jun/13/premier-league-restart-preview-no-11-manchester-city?CMP=share_btn_tw",
          display_url: "theguardian.com/football/2020/…",
          indices: [73, 96],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 46403451,
      id_str: "46403451",
      name: "Guardian sport",
      screen_name: "guardian_sport",
      location: "London",
      description:
        "Sport news, comment, video and more from the @Guardian. For all your US sports needs, follow @GdnUSsports, and Australian sport @GdnAusSport. IG: guardian_sport",
      url: "https://t.co/YJoNLFSjE2",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YJoNLFSjE2",
              expanded_url: "http://www.theguardian.com/sport",
              display_url: "theguardian.com/sport",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 814882,
      friends_count: 1759,
      listed_count: 8745,
      created_at: "Thu Jun 11 14:55:04 +0000 2009",
      favourites_count: 296,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 209742,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/46403451/1542987487",
      profile_link_color: "005689",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 5,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:18:02 +0000 2020",
    id: 1271688259299610600,
    id_str: "1271688259299610624",
    full_text:
      "Graeme Le Saux on life as a director at Real Mallorca: 'When the players came back, they were like kids in a sweet shop.' By @sidlowe https://t.co/rf87aGuAFM",
    truncated: false,
    display_text_range: [0, 157],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "sidlowe",
          name: "Sid Lowe",
          id: 108957853,
          id_str: "108957853",
          indices: [125, 133],
        },
      ],
      urls: [
        {
          url: "https://t.co/rf87aGuAFM",
          expanded_url:
            "https://www.theguardian.com/football/2020/jun/12/graeme-le-saux-when-the-players-came-back-they-were-like-kids-in-a-sweet-shop?CMP=share_btn_tw",
          display_url: "theguardian.com/football/2020/…",
          indices: [134, 157],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 46403451,
      id_str: "46403451",
      name: "Guardian sport",
      screen_name: "guardian_sport",
      location: "London",
      description:
        "Sport news, comment, video and more from the @Guardian. For all your US sports needs, follow @GdnUSsports, and Australian sport @GdnAusSport. IG: guardian_sport",
      url: "https://t.co/YJoNLFSjE2",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YJoNLFSjE2",
              expanded_url: "http://www.theguardian.com/sport",
              display_url: "theguardian.com/sport",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 814882,
      friends_count: 1759,
      listed_count: 8745,
      created_at: "Thu Jun 11 14:55:04 +0000 2009",
      favourites_count: 296,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 209742,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/46403451/1542987487",
      profile_link_color: "005689",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 3,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:15:30 +0000 2020",
    id: 1271687623476744200,
    id_str: "1271687623476744200",
    full_text:
      "Tottenham’s Hugo Lloris: ‘We finished the season on our knees. You don't have time to recover.’ By @DaveHytner https://t.co/0UEoVgnh9L",
    truncated: false,
    display_text_range: [0, 134],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "DaveHytner",
          name: "David Hytner",
          id: 595406077,
          id_str: "595406077",
          indices: [99, 110],
        },
      ],
      urls: [
        {
          url: "https://t.co/0UEoVgnh9L",
          expanded_url:
            "https://www.theguardian.com/football/2020/jun/12/hugo-lloris-difficult-to-stay-stable-spurs-premier-league-return?CMP=share_btn_tw",
          display_url: "theguardian.com/football/2020/…",
          indices: [111, 134],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 46403451,
      id_str: "46403451",
      name: "Guardian sport",
      screen_name: "guardian_sport",
      location: "London",
      description:
        "Sport news, comment, video and more from the @Guardian. For all your US sports needs, follow @GdnUSsports, and Australian sport @GdnAusSport. IG: guardian_sport",
      url: "https://t.co/YJoNLFSjE2",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YJoNLFSjE2",
              expanded_url: "http://www.theguardian.com/sport",
              display_url: "theguardian.com/sport",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 814882,
      friends_count: 1759,
      listed_count: 8745,
      created_at: "Thu Jun 11 14:55:04 +0000 2009",
      favourites_count: 296,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 209742,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1065992924566077441/5iDfDrqi_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/46403451/1542987487",
      profile_link_color: "005689",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 3,
    favorite_count: 4,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:14:54 +0000 2020",
    id: 1271687470158143500,
    id_str: "1271687470158143491",
    full_text: "#repost graham522\niiii]; )' https://t.co/TLAxVQzaBV",
    truncated: false,
    display_text_range: [0, 51],
    entities: {
      hashtags: [{ text: "repost", indices: [0, 7] }],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/TLAxVQzaBV",
          expanded_url:
            "https://www.instagram.com/p/CBXWXlqD4IY/?igshid=1ukk45qxj3t8c",
          display_url: "instagram.com/p/CBXWXlqD4IY/…",
          indices: [28, 51],
        },
      ],
    },
    source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 22832029,
      id_str: "22832029",
      name: "Slash",
      screen_name: "Slash",
      location: "Los Angeles, CA",
      description:
        "The official Twitter of Slash iii]; )' \nOrder your copy of Living The Dream Tour Live now.\nhttps://t.co/qfHanbgKiT",
      url: "https://t.co/YjAvxFdolS",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/YjAvxFdolS",
              expanded_url: "http://slashonline.com",
              display_url: "slashonline.com",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [
            {
              url: "https://t.co/qfHanbgKiT",
              expanded_url: "http://linktr.ee/Slash",
              display_url: "linktr.ee/Slash",
              indices: [91, 114],
            },
          ],
        },
      },
      protected: false,
      followers_count: 3605209,
      friends_count: 750,
      listed_count: 17427,
      created_at: "Wed Mar 04 20:51:27 +0000 2009",
      favourites_count: 13048,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: true,
      statuses_count: 12330,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: true,
      profile_background_color: "FFFFFF",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1022134366888058882/I5JaHI4j_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1022134366888058882/I5JaHI4j_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/22832029/1563210024",
      profile_link_color: "F70000",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "000000",
      profile_text_color: "666666",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "regular",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 2,
    favorite_count: 40,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:12:40 +0000 2020",
    id: 1271686907903332400,
    id_str: "1271686907903332352",
    full_text:
      "Bayern could seal the #Bundesliga title this evening as the Bavarian side eye the treble.\n@WillGitt looks at Hansi Flick's aspirations.\nhttps://t.co/EiXo4kZwpW",
    truncated: false,
    display_text_range: [0, 159],
    entities: {
      hashtags: [{ text: "Bundesliga", indices: [22, 33] }],
      symbols: [],
      user_mentions: [
        {
          screen_name: "WillGitt",
          name: "Will Gittins",
          id: 277665866,
          id_str: "277665866",
          indices: [90, 99],
        },
      ],
      urls: [
        {
          url: "https://t.co/EiXo4kZwpW",
          expanded_url:
            "https://en.as.com/en/2020/06/12/football/1591958876_002361.html",
          display_url: "en.as.com/en/2020/06/12/…",
          indices: [136, 159],
        },
      ],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 601993521,
      id_str: "601993521",
      name: "AS English @ 🏡",
      screen_name: "English_AS",
      location: "Madrid, España",
      description:
        "Sports news in English from https://t.co/IVBMv9zwP9 Noticias deportivas en inglés de https://t.co/IVBMv9zwP9 (...and a little fun at times!)",
      url: "https://t.co/aFfULKGYXU",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/aFfULKGYXU",
              expanded_url: "https://en.as.com/en/",
              display_url: "en.as.com/en/",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [
            {
              url: "https://t.co/IVBMv9zwP9",
              expanded_url: "http://AS.com",
              display_url: "AS.com",
              indices: [28, 51],
            },
            {
              url: "https://t.co/IVBMv9zwP9",
              expanded_url: "http://AS.com",
              display_url: "AS.com",
              indices: [85, 108],
            },
          ],
        },
      },
      protected: false,
      followers_count: 172195,
      friends_count: 999,
      listed_count: 1964,
      created_at: "Thu Jun 07 14:21:35 +0000 2012",
      favourites_count: 2992,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 162962,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "202020",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1237323295252455425/W3KIJc-n_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1237323295252455425/W3KIJc-n_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/601993521/1591810309",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 3,
    favorite_count: 3,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 06:05:03 +0000 2020",
    id: 1271684990070210600,
    id_str: "1271684990070210562",
    full_text:
      "RT @RuthlessUx: My experience has been when you have nothing to lose you're more honest &amp; authentic. As you gain comforts that fire fizzles…",
    truncated: false,
    display_text_range: [0, 144],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "RuthlessUx",
          name: "Shaheena Attarwala شاہینہ",
          id: 17711741,
          id_str: "17711741",
          indices: [3, 14],
        },
      ],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1454582852,
      id_str: "1454582852",
      name: "Soham Kamani",
      screen_name: "SohamKamani",
      location: "Bengaluru, India",
      description: "Developer, blogger and gardener. \nWorking at @gojektech",
      url: "https://t.co/Hd9DeeO3O1",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/Hd9DeeO3O1",
              expanded_url: "http://sohamkamani.com",
              display_url: "sohamkamani.com",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 883,
      friends_count: 387,
      listed_count: 52,
      created_at: "Fri May 24 15:54:32 +0000 2013",
      favourites_count: 626,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1558,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "000000",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/799587314854834176/RJnCKZnB_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/799587314854834176/RJnCKZnB_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1454582852/1479471426",
      profile_link_color: "1A237E",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "000000",
      profile_text_color: "000000",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Fri Jun 12 21:20:02 +0000 2020",
      id: 1271552865958367200,
      id_str: "1271552865958367238",
      full_text:
        "My experience has been when you have nothing to lose you're more honest &amp; authentic. As you gain comforts that fire fizzles. You then try and retro fit into a world where you work towards retaining what you have by compromising on values. It takes selfawarenss to be authentic.",
      truncated: false,
      display_text_range: [0, 281],
      entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 17711741,
        id_str: "17711741",
        name: "Shaheena Attarwala شاہینہ",
        screen_name: "RuthlessUx",
        location: "Bengaluru, India",
        description:
          "Designer, Lawyer, Activist & Empricist\n⛳ Mission to 'Democratize Design'🚀\n🙆‍♀️ Design @zoomcarindia\n❤ History Politics Poetry\n🔥University of Hard Knocks",
        url: "https://t.co/guJ93ca3GJ",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/guJ93ca3GJ",
                expanded_url: "http://www.RuthlessUx.com",
                display_url: "RuthlessUx.com",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 2795,
        friends_count: 2721,
        listed_count: 144,
        created_at: "Fri Nov 28 16:27:22 +0000 2008",
        favourites_count: 1815,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 4664,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFFFFF",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme11/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme11/bg.gif",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1059045178197995522/ko8oojDf_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1059045178197995522/ko8oojDf_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/17711741/1569001686",
        profile_link_color: "1B95E0",
        profile_sidebar_border_color: "EEEEEE",
        profile_sidebar_fill_color: "EFEFEF",
        profile_text_color: "3B3B3B",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 5,
      favorite_count: 31,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    is_quote_status: false,
    retweet_count: 5,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 05:58:28 +0000 2020",
    id: 1271683334024900600,
    id_str: "1271683334024900608",
    full_text:
      "Zidane set to oversee his 200th Real Madrid game as head coach with tomorrow's #LaLiga clash vs. Eibar\n#RealMadridEibar \n\nhttps://t.co/CZJm2iHTji https://t.co/JWE5vAzypx",
    truncated: false,
    display_text_range: [0, 145],
    entities: {
      hashtags: [
        { text: "LaLiga", indices: [79, 86] },
        { text: "RealMadridEibar", indices: [103, 119] },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/CZJm2iHTji",
          expanded_url:
            "https://en.as.com/en/2020/06/12/football/1591997304_970495.html?autoplay=1",
          display_url: "en.as.com/en/2020/06/12/…",
          indices: [122, 145],
        },
      ],
      media: [
        {
          id: 1271682645626364000,
          id_str: "1271682645626363904",
          indices: [146, 169],
          media_url: "http://pbs.twimg.com/media/EaXsoOeWoAAp-MS.jpg",
          media_url_https: "https://pbs.twimg.com/media/EaXsoOeWoAAp-MS.jpg",
          url: "https://t.co/JWE5vAzypx",
          display_url: "pic.twitter.com/JWE5vAzypx",
          expanded_url:
            "https://twitter.com/English_AS/status/1271683334024900608/photo/1",
          type: "photo",
          sizes: {
            large: { w: 750, h: 1037, resize: "fit" },
            thumb: { w: 150, h: 150, resize: "crop" },
            medium: { w: 750, h: 1037, resize: "fit" },
            small: { w: 492, h: 680, resize: "fit" },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1271682645626364000,
          id_str: "1271682645626363904",
          indices: [146, 169],
          media_url: "http://pbs.twimg.com/media/EaXsoOeWoAAp-MS.jpg",
          media_url_https: "https://pbs.twimg.com/media/EaXsoOeWoAAp-MS.jpg",
          url: "https://t.co/JWE5vAzypx",
          display_url: "pic.twitter.com/JWE5vAzypx",
          expanded_url:
            "https://twitter.com/English_AS/status/1271683334024900608/photo/1",
          type: "photo",
          sizes: {
            large: { w: 750, h: 1037, resize: "fit" },
            thumb: { w: 150, h: 150, resize: "crop" },
            medium: { w: 750, h: 1037, resize: "fit" },
            small: { w: 492, h: 680, resize: "fit" },
          },
        },
      ],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 601993521,
      id_str: "601993521",
      name: "AS English @ 🏡",
      screen_name: "English_AS",
      location: "Madrid, España",
      description:
        "Sports news in English from https://t.co/IVBMv9zwP9 Noticias deportivas en inglés de https://t.co/IVBMv9zwP9 (...and a little fun at times!)",
      url: "https://t.co/aFfULKGYXU",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/aFfULKGYXU",
              expanded_url: "https://en.as.com/en/",
              display_url: "en.as.com/en/",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [
            {
              url: "https://t.co/IVBMv9zwP9",
              expanded_url: "http://AS.com",
              display_url: "AS.com",
              indices: [28, 51],
            },
            {
              url: "https://t.co/IVBMv9zwP9",
              expanded_url: "http://AS.com",
              display_url: "AS.com",
              indices: [85, 108],
            },
          ],
        },
      },
      protected: false,
      followers_count: 172195,
      friends_count: 999,
      listed_count: 1964,
      created_at: "Thu Jun 07 14:21:35 +0000 2012",
      favourites_count: 2992,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 162962,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "202020",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1237323295252455425/W3KIJc-n_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1237323295252455425/W3KIJc-n_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/601993521/1591810309",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "FFFFFF",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 9,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 05:47:49 +0000 2020",
    id: 1271680656393875500,
    id_str: "1271680656393875456",
    full_text: "RT @SulafaJ: Me as a business owner: https://t.co/YfYfgAJOi0",
    truncated: false,
    display_text_range: [0, 60],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "SulafaJ",
          name: "Sulafa Al-jishi",
          id: 152729760,
          id_str: "152729760",
          indices: [3, 11],
        },
      ],
      urls: [],
      media: [
        {
          id: 1270965941719965700,
          id_str: "1270965941719965698",
          indices: [37, 60],
          media_url: "http://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
          media_url_https: "https://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
          url: "https://t.co/YfYfgAJOi0",
          display_url: "pic.twitter.com/YfYfgAJOi0",
          expanded_url:
            "https://twitter.com/SulafaJ/status/1270965947415891969/photo/1",
          type: "photo",
          sizes: {
            thumb: { w: 150, h: 150, resize: "crop" },
            small: { w: 628, h: 327, resize: "fit" },
            medium: { w: 628, h: 327, resize: "fit" },
            large: { w: 628, h: 327, resize: "fit" },
          },
          source_status_id: 1270965947415892000,
          source_status_id_str: "1270965947415891969",
          source_user_id: 152729760,
          source_user_id_str: "152729760",
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1270965941719965700,
          id_str: "1270965941719965698",
          indices: [37, 60],
          media_url: "http://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
          media_url_https: "https://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
          url: "https://t.co/YfYfgAJOi0",
          display_url: "pic.twitter.com/YfYfgAJOi0",
          expanded_url:
            "https://twitter.com/SulafaJ/status/1270965947415891969/photo/1",
          type: "photo",
          sizes: {
            thumb: { w: 150, h: 150, resize: "crop" },
            small: { w: 628, h: 327, resize: "fit" },
            medium: { w: 628, h: 327, resize: "fit" },
            large: { w: 628, h: 327, resize: "fit" },
          },
          source_status_id: 1270965947415892000,
          source_status_id_str: "1270965947415891969",
          source_user_id: 152729760,
          source_user_id_str: "152729760",
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 833518110,
      id_str: "833518110",
      name: "Four",
      screen_name: "FadTay4",
      location: "",
      description: "Child at Heart. Wallflower. I love a good quote.",
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 153,
      friends_count: 154,
      listed_count: 2,
      created_at: "Wed Sep 19 15:04:32 +0000 2012",
      favourites_count: 2029,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 9225,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: true,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1033778602079412225/2lzOFcTN_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1033778602079412225/2lzOFcTN_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/833518110/1447060444",
      profile_link_color: "0088FF",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Thu Jun 11 06:27:49 +0000 2020",
      id: 1270965947415892000,
      id_str: "1270965947415891969",
      full_text: "Me as a business owner: https://t.co/YfYfgAJOi0",
      truncated: false,
      display_text_range: [0, 23],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [],
        media: [
          {
            id: 1270965941719965700,
            id_str: "1270965941719965698",
            indices: [24, 47],
            media_url: "http://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
            media_url_https: "https://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
            url: "https://t.co/YfYfgAJOi0",
            display_url: "pic.twitter.com/YfYfgAJOi0",
            expanded_url:
              "https://twitter.com/SulafaJ/status/1270965947415891969/photo/1",
            type: "photo",
            sizes: {
              thumb: { w: 150, h: 150, resize: "crop" },
              small: { w: 628, h: 327, resize: "fit" },
              medium: { w: 628, h: 327, resize: "fit" },
              large: { w: 628, h: 327, resize: "fit" },
            },
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1270965941719965700,
            id_str: "1270965941719965698",
            indices: [24, 47],
            media_url: "http://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
            media_url_https: "https://pbs.twimg.com/media/EaNgykXWoAImp2Y.jpg",
            url: "https://t.co/YfYfgAJOi0",
            display_url: "pic.twitter.com/YfYfgAJOi0",
            expanded_url:
              "https://twitter.com/SulafaJ/status/1270965947415891969/photo/1",
            type: "photo",
            sizes: {
              thumb: { w: 150, h: 150, resize: "crop" },
              small: { w: 628, h: 327, resize: "fit" },
              medium: { w: 628, h: 327, resize: "fit" },
              large: { w: 628, h: 327, resize: "fit" },
            },
          },
        ],
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 152729760,
        id_str: "152729760",
        name: "Sulafa Al-jishi",
        screen_name: "SulafaJ",
        location: "أرض الله الواسعة",
        description: "SNS'15, PMU’19* {Laughter is the best medicine}",
        url: "https://t.co/lAPRNdpYhZ",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/lAPRNdpYhZ",
                expanded_url: "https://curiouscat.me/SulafaJ",
                display_url: "curiouscat.me/SulafaJ",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 775,
        friends_count: 222,
        listed_count: 2,
        created_at: "Sun Jun 06 18:45:32 +0000 2010",
        favourites_count: 1639,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 32949,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFFFFF",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1266115823078440962/KytIdL3q_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1266115823078440962/KytIdL3q_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/152729760/1569406767",
        profile_link_color: "F7598E",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 636,
      favorite_count: 1342,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: "en",
    },
    is_quote_status: false,
    retweet_count: 636,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 05:46:18 +0000 2020",
    id: 1271680271256031200,
    id_str: "1271680271256031232",
    full_text:
      'RT @Complex: "I can\'t breathe," a black man tells an Oklahoma City cop, "I don\'t care," the cop responds.\n\nDerrick Scott then died. He was…',
    truncated: false,
    display_text_range: [0, 139],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Complex",
          name: "Complex",
          id: 13049362,
          id_str: "13049362",
          indices: [3, 11],
        },
      ],
      urls: [],
    },
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 833518110,
      id_str: "833518110",
      name: "Four",
      screen_name: "FadTay4",
      location: "",
      description: "Child at Heart. Wallflower. I love a good quote.",
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 153,
      friends_count: 154,
      listed_count: 2,
      created_at: "Wed Sep 19 15:04:32 +0000 2012",
      favourites_count: 2029,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 9225,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: true,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1033778602079412225/2lzOFcTN_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1033778602079412225/2lzOFcTN_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/833518110/1447060444",
      profile_link_color: "0088FF",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Thu Jun 11 17:56:37 +0000 2020",
      id: 1271139286344249300,
      id_str: "1271139286344249345",
      full_text:
        '"I can\'t breathe," a black man tells an Oklahoma City cop, "I don\'t care," the cop responds.\n\nDerrick Scott then died. He was 42. https://t.co/YPEXGOg5u9 https://t.co/PkoGgw6YLL',
      truncated: false,
      display_text_range: [0, 153],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [
          {
            url: "https://t.co/YPEXGOg5u9",
            expanded_url: "https://bit.ly/3dVqddI",
            display_url: "bit.ly/3dVqddI",
            indices: [130, 153],
          },
        ],
        media: [
          {
            id: 1271138932839809000,
            id_str: "1271138932839809024",
            indices: [154, 177],
            media_url: "http://pbs.twimg.com/media/EaP-H-gWAAABxMY.png",
            media_url_https: "https://pbs.twimg.com/media/EaP-H-gWAAABxMY.png",
            url: "https://t.co/PkoGgw6YLL",
            display_url: "pic.twitter.com/PkoGgw6YLL",
            expanded_url:
              "https://twitter.com/Complex/status/1271139286344249345/photo/1",
            type: "photo",
            sizes: {
              medium: { w: 790, h: 521, resize: "fit" },
              large: { w: 790, h: 521, resize: "fit" },
              small: { w: 680, h: 448, resize: "fit" },
              thumb: { w: 150, h: 150, resize: "crop" },
            },
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1271138932839809000,
            id_str: "1271138932839809024",
            indices: [154, 177],
            media_url: "http://pbs.twimg.com/media/EaP-H-gWAAABxMY.png",
            media_url_https: "https://pbs.twimg.com/media/EaP-H-gWAAABxMY.png",
            url: "https://t.co/PkoGgw6YLL",
            display_url: "pic.twitter.com/PkoGgw6YLL",
            expanded_url:
              "https://twitter.com/Complex/status/1271139286344249345/photo/1",
            type: "photo",
            sizes: {
              medium: { w: 790, h: 521, resize: "fit" },
              large: { w: 790, h: 521, resize: "fit" },
              small: { w: 680, h: 448, resize: "fit" },
              thumb: { w: 150, h: 150, resize: "crop" },
            },
          },
        ],
      },
      source:
        '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 13049362,
        id_str: "13049362",
        name: "Complex",
        screen_name: "Complex",
        location: "New York",
        description: "Making Culture Pop.",
        url: "https://t.co/jPEji9tZYr",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/jPEji9tZYr",
                expanded_url: "http://www.complex.com",
                display_url: "complex.com",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 2260991,
        friends_count: 734,
        listed_count: 7935,
        created_at: "Mon Feb 04 14:34:39 +0000 2008",
        favourites_count: 26928,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: true,
        statuses_count: 340291,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: true,
        profile_background_color: "000000",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/839858358920310785/JVgCbSHx_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/839858358920310785/JVgCbSHx_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/13049362/1591156909",
        profile_link_color: "FF0000",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "F2F2F2",
        profile_text_color: "787878",
        profile_use_background_image: false,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 97140,
      favorite_count: 126206,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: "en",
    },
    is_quote_status: false,
    retweet_count: 97140,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Sat Jun 13 05:43:46 +0000 2020",
    id: 1271679637278429200,
    id_str: "1271679637278429189",
    full_text:
      "A Jewish writer for a Jewish magazine conducts a lengthy face-to-face interview with the person who coined the phrase “the Jews will not replace us.”\n\nOne of the most astonishing things I’ve read all year. The ending is... chilling. https://t.co/HrBWf41ymc",
    truncated: false,
    display_text_range: [0, 232],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: "https://t.co/HrBWf41ymc",
          expanded_url:
            "https://twitter.com/tabletmag/status/1271132590406279174",
          display_url: "twitter.com/tabletmag/stat…",
          indices: [233, 256],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 21782915,
      id_str: "21782915",
      name: "Andrew Clark",
      screen_name: "acdlite",
      location: "San Francisco, CA",
      description: "#BlackLivesMatter. @reactjs core at Facebook. He/him. Hi!",
      url: "https://t.co/6nE7CgrAuE",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/6nE7CgrAuE",
              expanded_url: "https://github.com/acdlite",
              display_url: "github.com/acdlite",
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 52722,
      friends_count: 1778,
      listed_count: 904,
      created_at: "Tue Feb 24 18:58:55 +0000 2009",
      favourites_count: 12902,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 18074,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "C0DEED",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1268659839917408256/XrxRXwCd_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1268659839917408256/XrxRXwCd_normal.jpg",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1271132590406279200,
    quoted_status_id_str: "1271132590406279174",
    quoted_status_permalink: {
      url: "https://t.co/HrBWf41ymc",
      expanded: "https://twitter.com/tabletmag/status/1271132590406279174",
      display: "twitter.com/tabletmag/stat…",
    },
    quoted_status: {
      created_at: "Thu Jun 11 17:30:00 +0000 2020",
      id: 1271132590406279200,
      id_str: "1271132590406279174",
      full_text:
        "American Racist: David Samuels interrogates Kevin MacDonald, perhaps the country’s most influential anti-Semite and racist ideologue https://t.co/KDmPskLdi7",
      truncated: false,
      display_text_range: [0, 156],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [
          {
            url: "https://t.co/KDmPskLdi7",
            expanded_url:
              "https://www.tabletmag.com/sections/news/articles/kevin-macdonald-american-anti-semitism",
            display_url: "tabletmag.com/sections/news/…",
            indices: [133, 156],
          },
        ],
      },
      source:
        '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 28254715,
        id_str: "28254715",
        name: "Tablet Magazine",
        screen_name: "tabletmag",
        location: "Published in New York City",
        description:
          "The daily online magazine of Jewish news, ideas, and culture. Subscribe to our podcast 'Unorthodox' today!",
        url: "https://t.co/vwLGH8FfZZ",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/vwLGH8FfZZ",
                expanded_url: "http://www.tabletmag.com",
                display_url: "tabletmag.com",
                indices: [0, 23],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 61025,
        friends_count: 4284,
        listed_count: 1363,
        created_at: "Thu Apr 02 01:57:51 +0000 2009",
        favourites_count: 22397,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: true,
        statuses_count: 39589,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FCFCFC",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1227992033106722822/t1B8-isC_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1227992033106722822/t1B8-isC_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/28254715/1575396761",
        profile_link_color: "39352F",
        profile_sidebar_border_color: "030303",
        profile_sidebar_fill_color: "FCFCFC",
        profile_text_color: "050505",
        profile_use_background_image: false,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 20,
      favorite_count: 60,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: "en",
    },
    retweet_count: 0,
    favorite_count: 8,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: "en",
  },
];
